// <auto-generated />
using Dopamine_API_Data_DOTNET5;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dopamine_API_DOTNET5.Migrations
{
    [DbContext(typeof(DopamineContext))]
    partial class DopamineContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.14");

            modelBuilder.Entity("Dopamine_API_Data_DOTNET5.PlayerData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("points")
                        .HasColumnType("INTEGER");

                    b.Property<int>("pointsToBeAdded")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PlayerData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            points = 10L,
                            pointsToBeAdded = 0
                        });
                });

            modelBuilder.Entity("Dopamine_API_Data_DOTNET5.Upgrades", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildingOne")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildingTwo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PlayerData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuildingOne = 1,
                            BuildingTwo = 0
                        });
                });

            modelBuilder.Entity("Dopamine_API_Data_DOTNET5.Upgrades", b =>
                {
                    b.HasOne("Dopamine_API_Data_DOTNET5.PlayerData", "PlayerData")
                        .WithOne("Upgrades")
                        .HasForeignKey("Dopamine_API_Data_DOTNET5.Upgrades", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerData");
                });

            modelBuilder.Entity("Dopamine_API_Data_DOTNET5.PlayerData", b =>
                {
                    b.Navigation("Upgrades");
                });
#pragma warning restore 612, 618
        }
    }
}
